server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sumtsov/currency-operations-spring-cloud-kubernetes.git
          search-paths: spring-cloud/git-config-repo
