apiVersion: v1
kind: Service
metadata:
  labels:
    app: limits
  name: limits
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: 8080
  selector:
    app: limits
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: limits
  name: limits
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: limits
  template:
    metadata:
      labels:
        app: limits
    spec:
      containers:
      - name: limits-service
        image: sumtsov/limits-service:0.0.2-SNAPSHOT
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/readiness
        livenessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/liveness
        envFrom:
          - configMapRef:
              name: limits 
      restartPolicy: Always  