server:
  port: 8000

spring:
  application:
    name: currency-exchange-service
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  sleuth:
    sampler:
      probability: 1.0

springdoc:
  swagger-ui:
    path: /currency-exchange/swagger-ui.html
  api-docs:
    path: /currency-exchange/v3/api-docs
