server:
  port: 8100

spring:
  application:
    name: currency-conversion-service
  sleuth:
    sampler:
      probability: 1.0

springdoc:
  swagger-ui:
    path: /currency-conversion/swagger-ui.html
  api-docs:
    path: /currency-conversion/v3/api-docs

app:
  currency-exchange:
    url: ${CURRENCY_EXCHANGE_URI:http://localhost}:8000
  limits:
    url: ${LIMITS_URI:http://localhost}:8080

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

