version: '3.8'

services: 
    currency-exchange-service:
        image: sumtsov/currency-exchange-service:0.0.1-SNAPSHOT
        ports: 
            - "8000:8000"
        networks: 
            - currency-network
        environment: 
            EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka 
            SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
            RABBIT_URI: amqp://guest:guest@rabbitmq:5672
            SPRING_RABBITMQ_HOST: rabbitmq
            SPRING_ZIPKIN_SENDER_TYPE: rabbit
        depends_on: 
            naming-server:
                condition: service_healthy
            rabbitmq:
                condition: service_healthy
        healthcheck:
            test: curl --fail --silent localhost:8000/actuator/health | grep UP || exit 1             
            
    currency-conversion-service:
        image: sumtsov/currency-conversion-service:0.0.1-SNAPSHOT
        ports: 
            - "8100:8100"
        networks: 
            - currency-network
        environment: 
            EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka 
            SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
            RABBIT_URI: amqp://guest:guest@rabbitmq:5672
            SPRING_RABBITMQ_HOST: rabbitmq
            SPRING_ZIPKIN_SENDER_TYPE: rabbit
        depends_on: 
            naming-server:
                condition: service_healthy
            rabbitmq:
                condition: service_healthy
        healthcheck:
            test: curl --fail --silent localhost:8100/actuator/health | grep UP || exit 1              

    api-gateway:
        image: sumtsov/api-gateway:0.0.1-SNAPSHOT
        ports: 
            - "8765:8765"
        networks: 
            - currency-network
        environment: 
            EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
            SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
            RABBIT_URI: amqp://guest:guest@rabbitmq:5672
            SPRING_RABBITMQ_HOST: rabbitmq
            SPRING_ZIPKIN_SENDER_TYPE: rabbit
        depends_on: 
            naming-server:
                condition: service_healthy
            rabbitmq:
                condition: service_healthy
        healthcheck:
            test: curl --fail --silent localhost:8765/actuator/health | grep UP || exit 1          

    limits-service:
        image: sumtsov/limits-service:0.0.1-SNAPSHOT     
        ports: 
            - "8080:8080"
        networks: 
            - currency-network
        environment: 
            EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
            SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
            SPRING_CLOUD_CONFIG_URI: http://config-server:8888
            RABBIT_URI: amqp://guest:guest@rabbitmq:5672
            SPRING_RABBITMQ_HOST: rabbitmq
            SPRING_ZIPKIN_SENDER_TYPE: rabbit
        depends_on: 
            config-server:
                condition: service_healthy
            naming-server:
                condition: service_healthy
            rabbitmq:
                condition: service_healthy
        healthcheck:
            test: curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1                   

    config-server:
        image: sumtsov/config-server:0.0.1-SNAPSHOT
        ports:
            - "8888:8888"
        networks:
            - currency-network
        environment:
            EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
        depends_on:
            naming-server:
                condition: service_healthy
        healthcheck:
            test: curl --fail --silent localhost:8888/actuator/health | grep UP || exit 1           
    
    naming-server:
        image: sumtsov/naming-server:0.0.1-SNAPSHOT
        ports: 
            - "8761:8761"
        networks: 
            - currency-network   
        healthcheck:
            test: curl --fail --silent localhost:8761/actuator/health | grep UP || exit 1    
        
    zipkin-server:
        image: openzipkin/zipkin:2.23
        ports: 
            - "9411:9411"
        networks: 
            - currency-network
        environment: 
            RABBIT_URI: amqp://guest:guest@rabbitmq:5672
        depends_on: 
            rabbitmq:
                condition: service_healthy   

    rabbitmq:
        image: rabbitmq:3.8.12-management
        ports: 
            - "5672:5672"
            - "15672:15672"  
        networks: 
            - currency-network
        healthcheck:    
            test: ["CMD", "rabbitmqctl", "status"]             

networks: 
    currency-network: